---
- assert: {that: "ansible_os_family == 'RedHat'"}

- name: "mysql removal"
  yum:
   name: mysql-server
   state: absent
- name: "mysql folder removal"
  file:
   path: /var/lib/mysql
   state: absent
   
- name: "Installing lamp and mysql python" 
  yum:
   name: "{{ item }}"
   state: present
  with_items: 
   - httpd
   - mysql-server
   - php
   - php-mysql
   - MySQL-python
  notify: 
    - httpd-restart
    - mysql-restart

- meta: flush_handlers

#- name: "Enabling Services"
#  service:
#   name: "{{ item }}"
#   state: restarted
#  with_items:
#   - httpd
#  - mysqld  
  
