---   
- name: "Adding virtual host entry"
  template: 
   src: vhost.j2
   dest: /etc/httpd/conf.d/{{domain}}.conf
      
- name: "Editing virtual host entry"
  lineinfile:
   dest: /etc/httpd/conf/httpd.conf
   regexp: '#NameVirtualHost\s+\*:80'
   line: 'NameVirtualHost *:80'

- name: "creating document root"
  file:
   path: /var/www/html/{{domain}} 
   state: directory
    
